server:
    port: 8080

spring:
    datasource:
        name: dev
        url: jdbc:mysql://localhost:3306/know_about_me?serverTimezone=GMT%2B8
        username: root
        password: 123456

mybatis:
    mapper-locations: "com/poldichen/knowaboutme/dao/mapper/*.xml"